version: '3.5'
services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    depends_on:
      - proxy
    restart: unless-stopped
  proxy:
    build: proxy
    restart: unless-stopped
